# Generated by Django 5.0.2 on 2024-03-09 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_inventory', '0002_remove_inventario_estado_producto_idestadoproducto'),
        ('mod_room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario_habitacion',
            name='ESTADO_PRODUCTO_IDESTADOPRODUCTO',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='mod_inventory.estado_producto'),
            preserve_default=False,
        ),
    ]
