# Generated by Django 4.2.7 on 2024-02-26 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_service', '0001_initial'),
        ('mod_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='factura',
            fields=[
                ('IDFACTURA', models.AutoField(primary_key=True, serialize=False)),
                ('FECHA_FACTURA', models.DateField()),
                ('MONTO_TOTAL_RESERVA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PERSONA_NRODOCUMENTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_user.persona')),
            ],
        ),
        migrations.CreateModel(
            name='metodo_pago',
            fields=[
                ('IDMETODOPAGO', models.AutoField(primary_key=True, serialize=False)),
                ('METODO', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='metodopago_factura',
            fields=[
                ('ID_METODO_FACTURA', models.AutoField(primary_key=True, serialize=False)),
                ('FACTURA_IDFACTURA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_invoice.factura')),
                ('METODO_PAGO_IDMETODOPAGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_invoice.metodo_pago')),
            ],
        ),
        migrations.CreateModel(
            name='detalles_factura',
            fields=[
                ('IDDETALLESFACTURA', models.AutoField(primary_key=True, serialize=False)),
                ('CANTIDAD', models.IntegerField()),
                ('FACTURA_IDFACTURA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_invoice.factura')),
                ('PRODUCTO_IDPRODUCTO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mod_service.producto')),
            ],
        ),
    ]
