# Generated by Django 5.0.2 on 2024-02-27 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mod_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='metodo_pago',
            fields=[
                ('IDMETODOPAGO', models.AutoField(primary_key=True, serialize=False)),
                ('METODO', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='factura',
            fields=[
                ('IDFACTURA', models.AutoField(primary_key=True, serialize=False)),
                ('FECHA_FACTURA', models.DateField()),
                ('MONTO_TOTAL_RESERVA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PERSONA_NRODOCUMENTO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='detalles_factura',
            fields=[
                ('IDDETALLESFACTURA', models.AutoField(primary_key=True, serialize=False)),
                ('CANTIDAD', models.IntegerField()),
                ('PRODUCTO_IDPRODUCTO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mod_service.producto')),
                ('FACTURA_IDFACTURA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_invoice.factura')),
            ],
        ),
        migrations.CreateModel(
            name='metodopago_factura',
            fields=[
                ('ID_METODO_FACTURA', models.AutoField(primary_key=True, serialize=False)),
                ('FACTURA_IDFACTURA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_invoice.factura')),
                ('METODO_PAGO_IDMETODOPAGO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_invoice.metodo_pago')),
            ],
        ),
    ]
