# Generated by Django 5.0.2 on 2024-03-19 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_invoice', '0001_initial'),
        ('mod_reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='PERSONA_NRODOCUMENTO',
        ),
        migrations.AddField(
            model_name='factura',
            name='IDRESERVA',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mod_reservation.reserva'),
            preserve_default=False,
        ),
    ]
