# Generated by Django 4.2.7 on 2024-02-26 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='estado_usuario',
            fields=[
                ('IDESTADO', models.AutoField(primary_key=True, serialize=False)),
                ('ESTADO', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_documento',
            fields=[
                ('IDTIPODOCUMENTO', models.AutoField(primary_key=True, serialize=False)),
                ('TIPO_DOCUMENTO', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_persona',
            fields=[
                ('IDTIPOPERSONA', models.AutoField(primary_key=True, serialize=False)),
                ('TIPO_PERSONA', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('NRODOCUMENTO', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NOMBRE', models.CharField(max_length=70)),
                ('APELLIDO', models.CharField(max_length=70)),
                ('EMAIL', models.EmailField(max_length=100, unique=True)),
                ('TELEFONO', models.CharField(max_length=15)),
                ('CONTRASENA', models.CharField(max_length=95)),
                ('ESTADO_USUARIO_IDESTADO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mod_user.estado_usuario')),
                ('TIPO_DOCUMENTO_IDTIPODOCUMENTO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mod_user.tipo_documento')),
                ('TIPO_PERSONA_IDTIPOPERSONA', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mod_user.tipo_persona')),
            ],
        ),
    ]
