# Generated by Django 5.0.2 on 2024-02-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='huesped',
            fields=[
                ('IDHUESPED', models.AutoField(primary_key=True, serialize=False)),
                ('NRODOCUMENTO', models.CharField(max_length=10)),
                ('NOMBRE', models.CharField(max_length=70)),
                ('APELLIDO', models.CharField(max_length=70)),
                ('EMAIL', models.EmailField(max_length=254, unique=True)),
                ('TELEFONO', models.CharField(max_length=15)),
            ],
        ),
    ]
