# Generated by Django 5.0.2 on 2024-03-09 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod_guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huesped',
            name='IDHUESPED',
        ),
        migrations.AlterField(
            model_name='huesped',
            name='APELLIDO',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='NOMBRE',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='NRODOCUMENTO',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='TELEFONO',
            field=models.CharField(max_length=12),
        ),
    ]
