# Generated by Django 5.0.2 on 2024-02-27 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria_inventario',
            fields=[
                ('IDCATEGORIA', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE_CATEGORIA', models.CharField(max_length=50)),
                ('DESCRIPCION', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='estado_producto',
            fields=[
                ('IDESTADOPRODUCTO', models.AutoField(primary_key=True, serialize=False)),
                ('ESTADO', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='inventario',
            fields=[
                ('IDINVENTARIO', models.AutoField(primary_key=True, serialize=False)),
                ('NOMBRE_PRODUCTO', models.CharField(max_length=60)),
                ('DESCRIPCION_PRODUCTO', models.TextField(max_length=300)),
                ('CATEGORIA_IDCATEGORIA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mod_inventory.categoria_inventario')),
                ('ESTADO_PRODUCTO_IDESTADOPRODUCTO', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mod_inventory.estado_producto')),
            ],
        ),
    ]
