# Generated by Django 5.0.2 on 2024-03-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='ESTADO_PRODUCTO_IDESTADOPRODUCTO',
        ),
    ]
